name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Ping Streamlit App
        run: |
          python streamlit_keep_alive.py